spring:
  datasource:
    hikari:
      initialization-fail-timeout: 60000
    url: jdbc:mysql://localhost:3307/pricingdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: pricinguser
    password: PricingPass123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8080

scheduling:
  enabled: true
